metricbeat.modules:
- module: redis
  enabled: false
  metricsets: ["info", "keyspace"]
  period: 10s

  # Redis hosts
  hosts: ["10.8.0.3:26379"]


- module: nginx
  enabled: false
  metricsets: ["stubstatus"]
  period: 10s

  # Nginx hosts
  hosts: ["http://127.0.0.1"]

  # Path to server status. Default nginx_status
  server_status_path: "nginx_status"

- module: postgresql
  enabled: true
  hosts: ["postgres://127.0.0.1:5432?sslmode=disable"]
  username: elastic
  password: changeme
  metricsets:
    # Stats about every PostgreSQL database
    - database

    # Stats about the background writer process's activity
    - bgwriter

    # Stats about every PostgreSQL process
    - activity

    - statements

output.elasticsearch:
  hosts: ["${ELASTICSEARCH_HOST}:9200"]
  username:
  password:

setup.dashboards:
  enabled: true

setup.kibana:
  host: "${KIBANA_HOST}:5601"
  username: ${ELASTICSEARCH_USERNAME}
  password: ${ELASTICSEARCH_PASSWORD}