filebeat:
  image: docker.elastic.co/beats/filebeat:7.6.2
  user: root
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /var/log/:/var/log/:ro
    - /var/lib/docker/containers/:/var/lib/docker/containers/:ro
    - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
    - ./filebeat:/usr/share/filebeat/data
  restart: always
  net: "host"
  environment:
    - ELASTICSEARCH_HOST=10.29.103.18
    - KIBANA_HOST=10.29.103.18
    - ELASTICSEARCH_USERNAME=elastic
    - ELASTICSEARCH_PASSWORD=changeme
  # disable strict permission checks
  command: ["--strict.perms=false"]

