# https://github.com/elastic/beats/blob/master/filebeat/filebeat.reference.yml

filebeat.modules:
- module: nginx
  access:
    enabled: true
    var.paths: ["/var/log/nginx/access.log"]
  error:
    enabled: true
    var.paths: ["/var/log/nginx/error.log"]

#filebeat.inputs:
#- type: docker
#  enabled: true
#  containers:
#    stream: all # can be all, stdout or stderr
#    ids:
#      - '*'

# exclude_lines: ["^\\s+[\\-`('.|_]"]  # drop asciiart lines
# multiline.pattern: "^\t|^[[:space:]]+(at|...)|^Caused by:"
# multiline.match: after

#- type: log
#  paths:
#    - /var/log/messages
#    - /var/log/*.log


#========================== Filebeat autodiscover ==============================
# See this URL on how to run Apache2 Filebeat module: # https://www.elastic.co/guide/en/beats/filebeat/current/running-on-docker.html
#filebeat.autodiscover:
#  providers:
#    - type: docker
      # https://www.elastic.co/guide/en/beats/filebeat/current/configuration-autodiscover-hints.html
      # This URL alos contains instructions on multi-line logs
#      hints.enabled: true



output.elasticsearch:
  hosts: ["${ELASTICSEARCH_HOST}:9200"]
  username: ${ELASTICSEARCH_USERNAME}
  password: ${ELASTICSEARCH_PASSWORD}

setup.dashboards:
  enabled: true

setup.kibana:
  host: "${KIBANA_HOST}:5601"
  username: ${ELASTICSEARCH_USERNAME}
  password: ${ELASTICSEARCH_PASSWORD}

